-- seed.sql — GENERIRANO. Ne uređivati ručno.
-- Izvor: context.md (izvoz) + hes-content.md (stablo kategorija).
-- Ponovna izgradnja: python scripts/seed.py
--
-- Pokretati NAKON shema.sql. Idempotentno je: ponovno pokretanje
-- osvježava vrijednosti umjesto da padne na duplikatu.

begin;

-- Kategorije prije artikala; podskupine referenciraju obitelj.
insert into kategorije (id, vrsta, roditelj_id, redoslijed, naziv_hr) values
  ('miniserveri', 'loxone', null, 0, 'Miniserveri'),
  ('prosirenja', 'loxone', null, 1, 'Proširenja'),
  ('doticajni-uredaji-i-tipkala', 'loxone', null, 2, 'Doticajni uređaji i tipkala'),
  ('senzori', 'loxone', null, 3, 'Senzori'),
  ('osvjetljenje', 'loxone', null, 4, 'Osvjetljenje'),
  ('upravljanje-osvjetljenjem', 'loxone', null, 5, 'Upravljanje osvjetljenjem'),
  ('audio-sustavi', 'loxone', null, 6, 'Audio sustavi'),
  ('aktuatori-i-pogoni', 'loxone', null, 7, 'Aktuatori i pogoni'),
  ('pametne-uticnice', 'loxone', null, 8, 'Pametne utičnice'),
  ('kabeli-i-konektori', 'loxone', null, 9, 'Kabeli i konektori'),
  ('dodatni-materijali', 'loxone', null, 10, 'Dodatni materijali'),
  ('ljestve-i-skele', 'alat', null, 0, 'Ljestve i skele'),
  ('rezanje-i-brusenje', 'alat', null, 1, 'Rezanje i brušenje'),
  ('busenje-i-odvijanje', 'alat', null, 2, 'Bušenje i odvijanje'),
  ('usisavaci-i-otprasivanje', 'alat', null, 3, 'Usisavači i otprašivanje'),
  ('upravljacke-jedinice', 'loxone', 'miniserveri', 0, 'Upravljačke jedinice'),
  ('ulazna-prosirenja', 'loxone', 'prosirenja', 0, 'Ulazna proširenja'),
  ('izlazna-prosirenja', 'loxone', 'prosirenja', 1, 'Izlazna proširenja'),
  ('komunikacijska-prosirenja', 'loxone', 'prosirenja', 2, 'Komunikacijska proširenja'),
  ('specijalizirana-prosirenja', 'loxone', 'prosirenja', 3, 'Specijalizirana proširenja'),
  ('touch-osnovna-serija', 'loxone', 'doticajni-uredaji-i-tipkala', 0, 'Touch osnovna serija'),
  ('touch-pure-serija', 'loxone', 'doticajni-uredaji-i-tipkala', 1, 'Touch pure serija'),
  ('nfc-i-sigurnost', 'loxone', 'doticajni-uredaji-i-tipkala', 2, 'NFC i sigurnost'),
  ('daljinsko-upravljanje', 'loxone', 'doticajni-uredaji-i-tipkala', 3, 'Daljinsko upravljanje'),
  ('detektori-pokreta-i-prisutnosti', 'loxone', 'senzori', 0, 'Detektori pokreta i prisutnosti'),
  ('senzori-klime-i-kvalitete-zraka', 'loxone', 'senzori', 1, 'Senzori klime i kvalitete zraka'),
  ('ostali-senzori', 'loxone', 'senzori', 2, 'Ostali senzori'),
  ('stropne-svjetljike', 'loxone', 'osvjetljenje', 0, 'Stropne svjetljike'),
  ('visece-svjetljike', 'loxone', 'osvjetljenje', 1, 'Viseće svjetljike'),
  ('stolne-svjetljike', 'loxone', 'osvjetljenje', 2, 'Stolne svjetljike'),
  ('led-trake', 'loxone', 'osvjetljenje', 3, 'LED trake'),
  ('led-bodovi-i-spotovi', 'loxone', 'osvjetljenje', 4, 'Led bodovi i spotovi'),
  ('upravljaci', 'loxone', 'upravljanje-osvjetljenjem', 0, 'Upravljači'),
  ('regulatori-intenziteta', 'loxone', 'upravljanje-osvjetljenjem', 1, 'Regulatori intenziteta'),
  ('zvucnici', 'loxone', 'audio-sustavi', 0, 'Zvučnici'),
  ('centralne-audio-jedinice', 'loxone', 'audio-sustavi', 1, 'Centralne audio jedinice'),
  ('zasjenjivanje', 'loxone', 'aktuatori-i-pogoni', 0, 'Zasjenjivanje'),
  ('ventili', 'loxone', 'aktuatori-i-pogoni', 1, 'Ventili'),
  ('wireless-uticnice', 'loxone', 'pametne-uticnice', 0, 'Wireless utičnice'),
  ('stezaljke', 'loxone', 'kabeli-i-konektori', 0, 'Stezaljke'),
  ('loxone-tree', 'loxone', 'kabeli-i-konektori', 1, 'Loxone tree'),
  ('memorija', 'loxone', 'dodatni-materijali', 0, 'Memorija'),
  ('nfc-sustav', 'loxone', 'dodatni-materijali', 1, 'NFC sustav')
on conflict (id) do update set
  vrsta = excluded.vrsta,
  roditelj_id = excluded.roditelj_id,
  redoslijed = excluded.redoslijed,
  naziv_hr = excluded.naziv_hr;

insert into artikli (id, vrsta, naziv, sku, marka, cijena_cents, osnova, na_stanju, slika, redoslijed) values
  ('1210', 'alat', 'PROTUBE-F360', 'PROTUBE-F360', 'Protube', 5000, 'dan', true, null, 0),
  ('1209', 'alat', 'K+K 235628', 'K+K 235628', 'K+K', 2000, 'dan', true, null, 1),
  ('1207', 'alat', 'K+K 235636', 'K+K 235636', 'K+K', 1600, 'dan', true, null, 2),
  ('1205', 'alat', 'Bosch GTS 10 J Professional', 'Bosch GTS 10 J Professional', 'Bosch', 2800, 'dan', true, null, 3),
  ('1201', 'alat', 'Bosch GAS 12-25 PL', 'Bosch GAS 12-25 PL', 'Bosch', 2800, 'dan', true, null, 4),
  ('1197', 'alat', 'Bosch GWS 18V-10', 'Bosch GWS 18V-10', 'Bosch', 2200, 'dan', true, null, 5),
  ('1194', 'alat', 'Bosch GSR 18V-55', 'Bosch GSR 18V-55', 'Bosch', 1600, 'dan', true, null, 6),
  ('1191', 'alat', 'Bosch GEX 18V-125', 'Bosch GEX 18V-125', 'Bosch', 2300, 'dan', true, null, 7),
  ('1188', 'alat', 'Bosch GRO 12V-35', 'Bosch GRO 12V-35', 'Bosch', 1600, 'dan', true, null, 8),
  ('1185', 'alat', 'Bosch Professional 12 V System', 'Bosch Professional 12 V System', 'Bosch', 2600, 'dan', true, null, 9),
  ('1180', 'alat', 'Bosch GKS 12V-26', 'Bosch GKS 12V-26', 'Bosch', 1800, 'dan', true, null, 10),
  ('1177', 'alat', 'Bosch GDS 18V-450 HC', 'Bosch GDS 18V-450 HC', 'Bosch', 3300, 'dan', true, null, 11),
  ('1176', 'alat', 'Bosch MA 55 – Nastavak magazina za izvijače', 'ma55', 'Bosch', 1000, 'dan', true, null, 12),
  ('1175', 'alat', 'Bosch GDR 12V-110', 'Bosch GDR 12V-110', 'Bosch', 1800, 'dan', true, null, 13),
  ('1170', 'alat', 'BOSCH GWS 12V-76', 'gws-18v', 'Bosch', 1800, 'dan', true, null, 14),
  ('1134', 'alat', 'Bosch-GSR-12V-15-FC', 'Bosch-GSR-12V-15-FC', 'Bosch', 1600, 'dan', true, null, 15),
  ('1808', 'loxone', 'SD kartica s FirmWareom za Miniserver Gen.1', 'SD kartica s FirmWareom za Miniserver Gen.1', 'Loxone', 1284, 'kom', true, null, 16),
  ('1805', 'loxone', 'NFC Key Fob Set (10)', 'NFC Key Fob Set (10)', 'Loxone', 3275, 'kom', true, null, 17),
  ('1802', 'loxone', 'Encrypted NFC Smart Cards Set (10)', 'Encrypted NFC Smart Cards Set (10)', 'Loxone', 3275, 'kom', true, null, 18),
  ('1800', 'loxone', 'Clamp Tree for NFC / Flex / Intercom (25)', 'Clamp Tree for NFC / Flex / Intercom (25)', 'Loxone', 1725, 'kom', true, null, 19),
  ('1797', 'loxone', 'Turbo Clamp (25)', 'Turbo Clamp (25)', 'Loxone', 1207, 'kom', true, null, 20),
  ('1794', 'loxone', 'Loxone Clamp Tree (25)', 'Loxone Clamp Tree (25)', 'Loxone', 1207, 'kom', true, null, 21),
  ('1790', 'loxone', 'Tree Cable (200m)', 'Tree Cable (200m)', 'Loxone', 34637, 'kom', true, null, 22),
  ('1786', 'loxone', 'Smart Socket Air Type G', 'Smart Socket Air Type G', 'Loxone', 6990, 'kom', true, null, 23),
  ('1782', 'loxone', 'Smart Socket Air Type J', 'Smart Socket Air Type J', 'Loxone', 6990, 'kom', true, null, 24),
  ('1779', 'loxone', 'Smart Socket Air Type F', 'Smart Socket Air Type F', 'Loxone', 7668, 'kom', true, null, 25),
  ('1776', 'loxone', 'Surface Box For 10 – Nadogradna kutija za zvučnik', 'Surface Box For 10 - Nadogradna kutija za zvučnik', 'Loxone', 15000, 'kom', true, null, 26),
  ('1773', 'loxone', 'Surface Box For 7 – Nadogradna kutija za zvučnik', 'Surface Box For 7 - Nadogradna kutija za zvučnik', 'Loxone', 13000, 'kom', true, null, 27),
  ('1770', 'loxone', 'Stereo Extension', 'Stereo Extension', 'Loxone', 25275, 'kom', true, null, 28),
  ('1767', 'loxone', 'Audio Server', 'Audio Server', 'Loxone', 50552, 'kom', true, null, 29),
  ('1762', 'loxone', 'Loxone Shading Actuator Air', 'Loxone Shading Actuator Air', 'Loxone', 11409, 'kom', true, null, 30),
  ('1759', 'loxone', 'Valve Actuator Air – Motorni pogon za ventile', 'Valve Actuator Air - Motorni pogon za ventile', 'Loxone', 10090, 'kom', true, null, 31),
  ('1755', 'loxone', 'Valve Actuator Tree – Motorni pogon za ventile', 'Valve Actuator Tree - Motorni pogon za ventile', 'Loxone', 8474, 'kom', true, null, 32),
  ('1746', 'loxone', 'IR Control Air', 'IR Control Air', 'Loxone', 11717, 'kom', true, null, 33),
  ('1743', 'loxone', 'Room Comfort Sensor Air', 'Room Comfort Sensor Air', 'Loxone', 9084, 'kom', true, null, 34),
  ('1740', 'loxone', 'Room Comfort Sensor Tree', 'Room Comfort Sensor Tree', 'Loxone', 24670, 'kom', true, null, 35),
  ('1737', 'loxone', 'Presence Sensor Air Senzor pristunosti', 'Presence Sensor Air Senzor pristunosti', 'Loxone', 10960, 'kom', true, null, 36),
  ('1733', 'loxone', 'Presence Sensor Tree Senzor prisutnosti', 'Presence Sensor Tree Senzor prisutnosti', 'Loxone', 9807, 'kom', true, null, 37),
  ('1729', 'loxone', 'Motion Sensor Tree Senzor pokreta', 'Motion Sensor Tree Senzor pokreta', 'Loxone', 10832, 'kom', true, null, 38),
  ('1726', 'loxone', 'Remote Air', 'Remote Air', 'Loxone', 10900, 'kom', true, null, 39),
  ('1722', 'loxone', 'NFC Code Touch Air', 'NFC Code Touch Air', 'Loxone', 30227, 'kom', true, null, 40),
  ('1718', 'loxone', 'NFC Code Touch Tree', 'NFC Code Touch Tree', 'Loxone', 30227, 'kom', true, null, 41),
  ('1715', 'loxone', 'Touch Air tipkalo', 'Touch Air tipkalo', 'Loxone', 11717, 'kom', true, null, 42),
  ('1712', 'loxone', 'Touch Tree tipkalo', 'Touch Tree tipkalo', 'Loxone', 9084, 'kom', true, null, 43),
  ('1709', 'loxone', 'Touch Pure Flex Air', 'Touch Pure Flex Air', 'Loxone', 21900, 'kom', true, null, 44),
  ('1706', 'loxone', 'Touch Pure for Nano tipkalo', 'Touch Pure for Nano tipkalo', 'Loxone', 21900, 'kom', true, null, 45),
  ('1702', 'loxone', 'Touch Pure Air stakleno tipkalo', 'Touch Pure Air stakleno tipkalo', 'Loxone', 19276, 'kom', true, null, 46),
  ('1700', 'loxone', 'Touch Pure Tree CO2 stakleno tipkalo', 'Touch Pure Tree CO2 stakleno tipkalo', 'Loxone', 23362, 'kom', true, null, 47),
  ('1697', 'loxone', 'Nano IO Air', 'Nano IO Air', 'Loxone', 11900, 'kom', true, null, 48),
  ('1693', 'loxone', 'Nano Dimmer Air', 'Nano Dimmer Air', 'Loxone', 12110, 'kom', true, null, 49),
  ('1689', 'loxone', 'RGBW 24V Dimmer Air', 'RGBW 24V Dimmer Air', 'Loxone', 9203, 'kom', true, null, 50),
  ('1684', 'loxone', 'RGBW 24V Dimmer Tree', 'RGBW 24V Dimmer Tree', 'Loxone', 7886, 'kom', true, null, 51),
  ('1520', 'loxone', 'Install Speaker 7 Master', 'Install Speaker 7 Master', 'Loxone', 29900, 'kom', true, null, 52),
  ('1516', 'loxone', 'Install speaker 7 passive', 'Install speaker 7 passive', 'Loxone', 12743, 'kom', true, null, 53),
  ('1512', 'loxone', 'RS485 extension', 'RS485 extension', 'Loxone', 18542, 'kom', true, null, 54),
  ('1508', 'loxone', 'LED Pendulum Slim RGBW PWM', 'LED Pendulum Slim RGBW PWM', 'Loxone', 24997, 'kom', true, null, 55),
  ('1505', 'loxone', 'Table lamp', 'Table lamp', 'Loxone', 19900, 'kom', true, null, 56),
  ('1502', 'loxone', 'LED strip RGBW', 'LED strip RGBW', 'Loxone', 13572, 'kom', true, null, 57),
  ('1497', 'loxone', 'LED Ceiling Light RGBW Air', 'LED Ceiling Light RGBW Air', 'Loxone', 31552, 'kom', true, null, 58),
  ('1491', 'loxone', 'LED spot RGBW Tree', 'LED spot RGBW Tree', 'Loxone', 8527, 'kom', true, null, 59),
  ('1487', 'loxone', 'KNX extension', 'KNX extension', 'Loxone', 57388, 'kom', true, null, 60),
  ('1482', 'loxone', 'AO extension', 'AO extension', 'Loxone', 27096, 'kom', true, null, 61),
  ('1478', 'loxone', 'AI extension', 'AI extension', 'Loxone', 20322, 'kom', true, null, 62),
  ('1474', 'loxone', 'Dali extension – 10 uređaja', 'Dali extension - 10 uređaja', 'Loxone', 20000, 'kom', true, null, 63),
  ('1470', 'loxone', 'Dali extension – 64 uređaja', 'Dali extension - 64 uređaja', null, 55445, 'kom', true, null, 64),
  ('1467', 'loxone', 'Modbus extension', 'Modbus extension', 'Loxone', 25011, 'kom', true, null, 65),
  ('1463', 'loxone', '1-wire extension', '1-wire extension', 'Loxone', 18542, 'kom', true, null, 66),
  ('1459', 'loxone', 'DI extension', 'DI extension', 'Loxone', 28460, 'kom', true, null, 67),
  ('1455', 'loxone', 'Dimmer extension', 'Dimmer extension', 'Loxone', 28460, 'kom', true, null, 68),
  ('1451', 'loxone', 'Relay extension', 'Relay extension', 'Loxone', 33757, 'kom', true, null, 69),
  ('1447', 'loxone', 'AIR base extension', 'AIR base extension', 'Loxone', 10861, 'kom', true, null, 70),
  ('1444', 'loxone', 'Tree extension', 'Tree extension', 'Loxone', 10861, 'kom', true, null, 71),
  ('1441', 'loxone', 'Miniserver Go', 'Miniserver Go', 'Loxone', 39362, 'kom', true, null, 72),
  ('1438', 'loxone', 'Miniserver Compact', 'Miniserver Compact', 'Loxone', 49500, 'kom', true, null, 73),
  ('1433', 'loxone', 'Miniserver', 'Miniserver', 'Loxone', 65561, 'kom', true, null, 74)
on conflict (id) do update set
  vrsta = excluded.vrsta,
  naziv = excluded.naziv,
  sku = excluded.sku,
  marka = excluded.marka,
  cijena_cents = excluded.cijena_cents,
  osnova = excluded.osnova,
  na_stanju = excluded.na_stanju,
  redoslijed = excluded.redoslijed;

-- Veze se brišu i pišu iznova: artikl je mogao promijeniti kategoriju,
-- a upsert sam po sebi ne bi maknuo staru vezu.
delete from artikl_kategorije;
insert into artikl_kategorije (artikl_id, kategorija_id) values
  ('1210', 'ljestve-i-skele'),
  ('1209', 'ljestve-i-skele'),
  ('1207', 'ljestve-i-skele'),
  ('1205', 'rezanje-i-brusenje'),
  ('1201', 'usisavaci-i-otprasivanje'),
  ('1197', 'rezanje-i-brusenje'),
  ('1194', 'busenje-i-odvijanje'),
  ('1191', 'rezanje-i-brusenje'),
  ('1188', 'rezanje-i-brusenje'),
  ('1185', 'busenje-i-odvijanje'),
  ('1180', 'rezanje-i-brusenje'),
  ('1177', 'busenje-i-odvijanje'),
  ('1176', 'busenje-i-odvijanje'),
  ('1175', 'busenje-i-odvijanje'),
  ('1170', 'rezanje-i-brusenje'),
  ('1134', 'busenje-i-odvijanje'),
  ('1808', 'dodatni-materijali'),
  ('1808', 'memorija'),
  ('1805', 'dodatni-materijali'),
  ('1805', 'nfc-sustav'),
  ('1802', 'dodatni-materijali'),
  ('1802', 'nfc-sustav'),
  ('1800', 'kabeli-i-konektori'),
  ('1800', 'stezaljke'),
  ('1797', 'kabeli-i-konektori'),
  ('1797', 'stezaljke'),
  ('1794', 'kabeli-i-konektori'),
  ('1794', 'stezaljke'),
  ('1790', 'kabeli-i-konektori'),
  ('1790', 'loxone-tree'),
  ('1786', 'pametne-uticnice'),
  ('1786', 'wireless-uticnice'),
  ('1782', 'pametne-uticnice'),
  ('1782', 'wireless-uticnice'),
  ('1779', 'pametne-uticnice'),
  ('1779', 'wireless-uticnice'),
  ('1776', 'audio-sustavi'),
  ('1776', 'zvucnici'),
  ('1773', 'audio-sustavi'),
  ('1773', 'zvucnici'),
  ('1770', 'audio-sustavi'),
  ('1770', 'centralne-audio-jedinice'),
  ('1767', 'audio-sustavi'),
  ('1767', 'centralne-audio-jedinice'),
  ('1762', 'aktuatori-i-pogoni'),
  ('1762', 'zasjenjivanje'),
  ('1759', 'aktuatori-i-pogoni'),
  ('1759', 'ventili'),
  ('1755', 'aktuatori-i-pogoni'),
  ('1755', 'ventili'),
  ('1746', 'ostali-senzori'),
  ('1746', 'senzori'),
  ('1743', 'senzori'),
  ('1743', 'senzori-klime-i-kvalitete-zraka'),
  ('1740', 'senzori'),
  ('1740', 'senzori-klime-i-kvalitete-zraka'),
  ('1737', 'detektori-pokreta-i-prisutnosti'),
  ('1737', 'senzori'),
  ('1733', 'detektori-pokreta-i-prisutnosti'),
  ('1733', 'senzori'),
  ('1729', 'detektori-pokreta-i-prisutnosti'),
  ('1729', 'senzori'),
  ('1726', 'daljinsko-upravljanje'),
  ('1726', 'doticajni-uredaji-i-tipkala'),
  ('1722', 'doticajni-uredaji-i-tipkala'),
  ('1722', 'nfc-i-sigurnost'),
  ('1718', 'doticajni-uredaji-i-tipkala'),
  ('1718', 'nfc-i-sigurnost'),
  ('1715', 'doticajni-uredaji-i-tipkala'),
  ('1715', 'touch-osnovna-serija'),
  ('1712', 'doticajni-uredaji-i-tipkala'),
  ('1712', 'touch-osnovna-serija'),
  ('1709', 'doticajni-uredaji-i-tipkala'),
  ('1709', 'touch-pure-serija'),
  ('1706', 'doticajni-uredaji-i-tipkala'),
  ('1706', 'touch-pure-serija'),
  ('1702', 'doticajni-uredaji-i-tipkala'),
  ('1702', 'touch-pure-serija'),
  ('1700', 'doticajni-uredaji-i-tipkala'),
  ('1700', 'touch-pure-serija'),
  ('1697', 'upravljaci'),
  ('1697', 'upravljanje-osvjetljenjem'),
  ('1693', 'regulatori-intenziteta'),
  ('1693', 'upravljanje-osvjetljenjem'),
  ('1689', 'regulatori-intenziteta'),
  ('1689', 'upravljanje-osvjetljenjem'),
  ('1684', 'regulatori-intenziteta'),
  ('1684', 'upravljanje-osvjetljenjem'),
  ('1520', 'audio-sustavi'),
  ('1520', 'zvucnici'),
  ('1516', 'audio-sustavi'),
  ('1516', 'zvucnici'),
  ('1512', 'prosirenja'),
  ('1512', 'specijalizirana-prosirenja'),
  ('1508', 'osvjetljenje'),
  ('1508', 'visece-svjetljike'),
  ('1505', 'osvjetljenje'),
  ('1505', 'stolne-svjetljike'),
  ('1502', 'led-trake'),
  ('1502', 'osvjetljenje'),
  ('1497', 'osvjetljenje'),
  ('1497', 'stropne-svjetljike'),
  ('1491', 'led-bodovi-i-spotovi'),
  ('1491', 'osvjetljenje'),
  ('1487', 'specijalizirana-prosirenja'),
  ('1487', 'prosirenja'),
  ('1482', 'prosirenja'),
  ('1482', 'specijalizirana-prosirenja'),
  ('1478', 'prosirenja'),
  ('1478', 'ulazna-prosirenja'),
  ('1474', 'prosirenja'),
  ('1474', 'specijalizirana-prosirenja'),
  ('1470', 'prosirenja'),
  ('1470', 'specijalizirana-prosirenja'),
  ('1467', 'prosirenja'),
  ('1467', 'specijalizirana-prosirenja'),
  ('1463', 'prosirenja'),
  ('1463', 'specijalizirana-prosirenja'),
  ('1459', 'prosirenja'),
  ('1459', 'ulazna-prosirenja'),
  ('1455', 'izlazna-prosirenja'),
  ('1455', 'prosirenja'),
  ('1451', 'izlazna-prosirenja'),
  ('1451', 'prosirenja'),
  ('1447', 'komunikacijska-prosirenja'),
  ('1447', 'prosirenja'),
  ('1444', 'komunikacijska-prosirenja'),
  ('1444', 'prosirenja'),
  ('1441', 'miniserveri'),
  ('1441', 'upravljacke-jedinice'),
  ('1438', 'miniserveri'),
  ('1438', 'upravljacke-jedinice'),
  ('1433', 'miniserveri'),
  ('1433', 'upravljacke-jedinice')
on conflict do nothing;

commit;
