/**
 * prijevodi.js — tekst koji crta JavaScript, na sva tri jezika.
 *
 * Staticki tekst stranica prevodi scripts/jezici.mjs iz data/i18n/*.json.
 * Ovdje stoji samo ono sto nastaje u pregledniku: kartice kataloga, ladica
 * kosarice, filtri, natpisi gumba. Da stoji u istim JSON datotekama, svaka
 * stranica bi ih morala dohvatiti prije prvog crtanja kataloga.
 *
 * Pravila koja vrijede i ovdje:
 *   - njemacki bez ß. Neue Regrade ga nema (scripts/provjere.py), pa se pise
 *     "ss": "schliessen", ne "schließen".
 *   - nazivi Loxone proizvoda se ne prevode.
 *   - nijedan jezik ne tvrdi nista sto hrvatski izvor ne tvrdi.
 *
 * Svaki jezik mora imati iste kljuceve — provjerava scripts/provjere.mjs.
 * Vrijednost moze biti niz znakova (za t()) ili objekt oblika mnozine
 * `{ one, few, other }` (za mnozina()).
 */

export const PRIJEVODI = {
  hr: {
    "mnozina.artikl": { one: "artikl", few: "artikla", other: "artikala" },
    "mnozina.dan": { one: "dan", few: "dana", other: "dana" },

    "katalog.skupine": "Skupine",
    "katalog.sve": "Sve",
    "katalog.marka": "Marka",
    "katalog.samo_na_stanju": "Samo na stanju",
    "katalog.ocisti": "Očistite filtre",
    "katalog.sort_zadano": "Zadano",
    "katalog.sort_cijena_asc": "Cijena rastuće",
    "katalog.sort_cijena_desc": "Cijena padajuće",
    "katalog.sort_naziv_asc": "Naziv A–Ž",
    "katalog.poredaj": "Poredaj",
    "katalog.poredaj_artikle": "Poredaj artikle",
    "katalog.po_danu": "po danu",
    "katalog.po_komadu": "po komadu",
    "katalog.dan_kratko": "dan",
    "katalog.manje_od": "Manje {naziv}",
    "katalog.vise_od": "Više {naziv}",
    "katalog.dodano": "Dodano u košaricu",
    "katalog.dodajte": "Dodajte u košaricu",
    "katalog.dodajte_naziv": "Dodajte {naziv} u košaricu",
    "katalog.na_stanju": "Na stanju",
    "katalog.na_upit": "Na upit",
    "katalog.nedostupno": "Trenutno nije u ponudi",
    "katalog.prazno": "Nema artikala za odabrane filtre.",
    "katalog.ucitavanje": "Učitavanje kataloga…",
    "katalog.greska": "Katalog se trenutno ne može učitati.",
    "katalog.greska_uputa": "Pokušajte osvježiti stranicu ili nam se javite na",
    "katalog.ukloni_filtar": "ukloni filtar",
    "katalog.filtri": "Filtri",
    "katalog.aktivnih": "aktivnih:",

    "galerija.video": "{naziv} — videoprikaz",
    "galerija.prikaz": "Prikaz {i} od {n}",
    "galerija.sve": "Sve",
    "galerija.svi_projekti": "Svi projekti",
    "galerija.fotografija": { one: "fotografija", few: "fotografije", other: "fotografija" },
    "galerija.projekt": { one: "projekt", few: "projekta", other: "projekata" },
    "galerija.prazno": "Trenutno nema fotografija.",
    "galerija.greska": "Galerija se trenutno ne može učitati.",
    "galerija.otvori": "Otvorite fotografiju: {opis}",
    "galerija.prethodna": "Prethodna fotografija",
    "galerija.sljedeca": "Sljedeća fotografija",
    "galerija.zatvori": "Zatvori",
    "galerija.brojac": "{i} / {n}",

    "usluga.industrijske": "Industrijske elektroinstalacije",
    "usluga.zavrsni": "Završni radovi",
    "usluga.kucne": "Kućne elektroinstalacije",
    "usluga.loxone": "Loxone smart home",

    "proizvod.prethodni": "Prethodni proizvodi",
    "proizvod.sljedeci": "Sljedeći proizvodi",

    "kosarica.naslov": "Košarica",
    "kosarica.zatvori": "Zatvori košaricu",
    "kosarica.prazna": "Košarica je prazna.",
    "kosarica.prazna_uputa": "Dodajte artikle iz Loxone kataloga ili najma alata pa zatražite ponudu.",
    "kosarica.loxone_katalog": "Loxone katalog",
    "kosarica.najam_alata": "Najam alata",
    "kosarica.ukloni": "Ukloni {naziv}",
    "kosarica.manje": "Manje",
    "kosarica.vise": "Više",
    "kosarica.razdoblje": "Razdoblje",
    "kosarica.sukob": "U odabranom razdoblju alat je zauzet.",
    "kosarica.sukobi": "Za {n} u najmu odabrano je zauzeto razdoblje.",

    "najam.slobodno_danas": "Slobodno danas",
    "najam.slobodno_od": "Slobodno od {datum}",
    "najam.vec_rezervirano": "Već rezervirano:",

    "kalendar.prethodni": "Prethodni mjesec",
    "kalendar.sljedeci": "Sljedeći mjesec",
    "kalendar.zatvori": "Zatvori kalendar",
    "kalendar.odaberite_pocetak": "Odaberite dan preuzimanja.",
    "kalendar.odaberite_kraj": "Odaberite dan povrata.",
    "kalendar.ucitavanje": "Učitavanje zauzetosti…",
    "kalendar.preuzimanje": "Preuzimanje",
    "kalendar.povrat": "Povrat",
    "kalendar.zauzeto": "zauzeto",
    "kalendar.legenda_zauzeto": "Zauzeto",
    "kalendar.ponisti": "Poništi",
    "kalendar.potvrdi": "Potvrdi",
    "kosarica.odaberite_datume": "Odaberite datume",
    "kosarica.ukupno": "Ukupno",
    "kosarica.proizvodi": "Proizvodi",
    "kosarica.proizvodi_natpis": "Loxone · cijena po komadu",
    "kosarica.najam_natpis": "cijena po danu",
    "kosarica.ograda": "Procjena na temelju cjenika. Konačnu ponudu šaljemo e-poštom.",
    "kosarica.nedostaju_datumi": "Za {n} u najmu nedostaju datumi.",
    "kosarica.zatrazite_ponudu": "Zatražite ponudu",
    "kosarica.isprazni": "Ispraznite košaricu",

    "izbornik.otvori": "Otvori izbornik",
    "izbornik.zatvori": "Zatvori izbornik",

    "tema.na_svijetlu": "Prebaci na svijetlu temu",
    "tema.na_tamnu": "Prebaci na tamnu temu",

    "obrazac.spremno": "Spremno za slanje",
    "obrazac.obavezno": "Ovo polje je obavezno.",
    "obrazac.email": "Provjerite adresu e-pošte.",
    "obrazac.poruka": "Ukratko opišite posao ili upit.",
    "obrazac.provjerite": "Provjerite označena polja.",
    "obrazac.salje": "Slanje…",
    "obrazac.poslano": "Upit je poslan.",
    "obrazac.poslano_najam": "Termin za alate iz košarice držimo 48 sati. Potvrdu ili odgovor šaljemo e-poštom.",
    "obrazac.greska": "Upit nije poslan. Pokušajte ponovno ili nam se javite na {email}.",
    "obrazac.zauzeto": "U odabranom razdoblju već je zauzeto: {popis}. Promijenite datume u košarici i pošaljite ponovno.",
    "obrazac.nedostupno": "Više nije u ponudi: {popis}. Uklonite iz košarice i pošaljite ponovno.",
    "obrazac.nedostaju_datumi": "Za najam u košarici nedostaju datumi.",
    "obrazac.otvori_kosaricu": "Otvorite košaricu",
    "obrazac.kosarica": "Upit uključuje {n} iz košarice.",
  },

  de: {
    "mnozina.artikl": { one: "Artikel", other: "Artikel" },
    "mnozina.dan": { one: "Tag", other: "Tage" },

    "katalog.skupine": "Gruppen",
    "katalog.sve": "Alle",
    "katalog.marka": "Marke",
    "katalog.samo_na_stanju": "Nur auf Lager",
    "katalog.ocisti": "Filter zurücksetzen",
    "katalog.sort_zadano": "Standard",
    "katalog.sort_cijena_asc": "Preis aufsteigend",
    "katalog.sort_cijena_desc": "Preis absteigend",
    "katalog.sort_naziv_asc": "Name A–Z",
    "katalog.poredaj": "Sortieren",
    "katalog.poredaj_artikle": "Artikel sortieren",
    "katalog.po_danu": "pro Tag",
    "katalog.po_komadu": "pro Stück",
    "katalog.dan_kratko": "Tag",
    "katalog.manje_od": "Menge verringern: {naziv}",
    "katalog.vise_od": "Menge erhöhen: {naziv}",
    "katalog.dodano": "In den Warenkorb gelegt",
    "katalog.dodajte": "In den Warenkorb",
    "katalog.dodajte_naziv": "{naziv} in den Warenkorb legen",
    "katalog.na_stanju": "Auf Lager",
    "katalog.na_upit": "Auf Anfrage",
    "katalog.nedostupno": "Derzeit nicht im Angebot",
    "katalog.prazno": "Keine Artikel für die gewählten Filter.",
    "katalog.ucitavanje": "Katalog wird geladen…",
    "katalog.greska": "Der Katalog kann gerade nicht geladen werden.",
    "katalog.greska_uputa": "Bitte laden Sie die Seite neu oder schreiben Sie uns an",
    "katalog.ukloni_filtar": "Filter entfernen",
    "katalog.filtri": "Filter",
    "katalog.aktivnih": "aktiv:",

    "galerija.video": "{naziv} — Video",
    "galerija.prikaz": "Ansicht {i} von {n}",
    "galerija.sve": "Alle",
    "galerija.svi_projekti": "Alle Projekte",
    "galerija.fotografija": { one: "Foto", other: "Fotos" },
    "galerija.projekt": { one: "Projekt", other: "Projekte" },
    "galerija.prazno": "Derzeit keine Fotos.",
    "galerija.greska": "Die Galerie kann gerade nicht geladen werden.",
    "galerija.otvori": "Foto öffnen: {opis}",
    "galerija.prethodna": "Vorheriges Foto",
    "galerija.sljedeca": "Nächstes Foto",
    "galerija.zatvori": "Schliessen",
    "galerija.brojac": "{i} / {n}",

    "usluga.industrijske": "Industrielle Elektroinstallationen",
    "usluga.zavrsni": "Ausbauarbeiten",
    "usluga.kucne": "Elektroinstallationen für Wohngebäude",
    "usluga.loxone": "Loxone Smart Home",

    "proizvod.prethodni": "Vorherige Produkte",
    "proizvod.sljedeci": "Nächste Produkte",

    "kosarica.naslov": "Warenkorb",
    "kosarica.zatvori": "Warenkorb schliessen",
    "kosarica.prazna": "Ihr Warenkorb ist leer.",
    "kosarica.prazna_uputa":
      "Legen Sie Artikel aus dem Loxone-Katalog oder der Werkzeugvermietung in den Warenkorb und fordern Sie ein Angebot an.",
    "kosarica.loxone_katalog": "Loxone-Katalog",
    "kosarica.najam_alata": "Werkzeugvermietung",
    "kosarica.ukloni": "{naziv} entfernen",
    "kosarica.manje": "Weniger",
    "kosarica.vise": "Mehr",
    "kosarica.razdoblje": "Zeitraum",
    "kosarica.sukob": "Im gewählten Zeitraum ist das Werkzeug belegt.",
    "kosarica.sukobi": "Für {n} ist der gewählte Zeitraum belegt.",

    "najam.slobodno_danas": "Heute frei",
    "najam.slobodno_od": "Frei ab {datum}",
    "najam.vec_rezervirano": "Bereits reserviert:",

    "kalendar.prethodni": "Vorheriger Monat",
    "kalendar.sljedeci": "Nächster Monat",
    "kalendar.zatvori": "Kalender schliessen",
    "kalendar.odaberite_pocetak": "Wählen Sie den Abholtag.",
    "kalendar.odaberite_kraj": "Wählen Sie den Rückgabetag.",
    "kalendar.ucitavanje": "Belegung wird geladen…",
    "kalendar.preuzimanje": "Abholung",
    "kalendar.povrat": "Rückgabe",
    "kalendar.zauzeto": "belegt",
    "kalendar.legenda_zauzeto": "Belegt",
    "kalendar.ponisti": "Zurücksetzen",
    "kalendar.potvrdi": "Übernehmen",
    "kosarica.odaberite_datume": "Zeitraum wählen",
    "kosarica.ukupno": "Gesamt",
    "kosarica.proizvodi": "Produkte",
    "kosarica.proizvodi_natpis": "Loxone · Preis pro Stück",
    "kosarica.najam_natpis": "Preis pro Tag",
    "kosarica.ograda": "Schätzung auf Basis der Preisliste. Das endgültige Angebot senden wir Ihnen per E-Mail.",
    "kosarica.nedostaju_datumi": "Für {n} fehlt der Mietzeitraum.",
    "kosarica.zatrazite_ponudu": "Angebot anfordern",
    "kosarica.isprazni": "Warenkorb leeren",

    "izbornik.otvori": "Menü öffnen",
    "izbornik.zatvori": "Menü schliessen",

    "tema.na_svijetlu": "Zum hellen Design wechseln",
    "tema.na_tamnu": "Zum dunklen Design wechseln",

    "obrazac.spremno": "Bereit zum Senden",
    "obrazac.obavezno": "Dieses Feld ist erforderlich.",
    "obrazac.email": "Bitte prüfen Sie die E-Mail-Adresse.",
    "obrazac.poruka": "Beschreiben Sie kurz den Auftrag oder Ihre Anfrage.",
    "obrazac.provjerite": "Bitte prüfen Sie die markierten Felder.",
    "obrazac.salje": "Wird gesendet…",
    "obrazac.poslano": "Ihre Anfrage wurde gesendet.",
    "obrazac.poslano_najam":
      "Den Zeitraum für die Werkzeuge aus dem Warenkorb halten wir 48 Stunden für Sie frei. Bestätigung oder Antwort senden wir per E-Mail.",
    "obrazac.greska": "Die Anfrage wurde nicht gesendet. Bitte versuchen Sie es erneut oder schreiben Sie uns an {email}.",
    "obrazac.zauzeto":
      "Im gewählten Zeitraum bereits vergeben: {popis}. Bitte ändern Sie die Daten im Warenkorb und senden Sie erneut.",
    "obrazac.nedostupno": "Nicht mehr im Angebot: {popis}. Bitte aus dem Warenkorb entfernen und erneut senden.",
    "obrazac.nedostaju_datumi": "Für die Miete im Warenkorb fehlt der Zeitraum.",
    "obrazac.otvori_kosaricu": "Warenkorb öffnen",
    "obrazac.kosarica": "Die Anfrage enthält {n} aus dem Warenkorb.",
  },

  en: {
    "mnozina.artikl": { one: "item", other: "items" },
    "mnozina.dan": { one: "day", other: "days" },

    "katalog.skupine": "Groups",
    "katalog.sve": "All",
    "katalog.marka": "Brand",
    "katalog.samo_na_stanju": "In stock only",
    "katalog.ocisti": "Clear filters",
    "katalog.sort_zadano": "Default",
    "katalog.sort_cijena_asc": "Price: low to high",
    "katalog.sort_cijena_desc": "Price: high to low",
    "katalog.sort_naziv_asc": "Name A–Z",
    "katalog.poredaj": "Sort",
    "katalog.poredaj_artikle": "Sort items",
    "katalog.po_danu": "per day",
    "katalog.po_komadu": "per unit",
    "katalog.dan_kratko": "day",
    "katalog.manje_od": "Decrease quantity: {naziv}",
    "katalog.vise_od": "Increase quantity: {naziv}",
    "katalog.dodano": "Added to cart",
    "katalog.dodajte": "Add to cart",
    "katalog.dodajte_naziv": "Add {naziv} to cart",
    "katalog.na_stanju": "In stock",
    "katalog.na_upit": "On request",
    "katalog.nedostupno": "Currently not available",
    "katalog.prazno": "No items match the selected filters.",
    "katalog.ucitavanje": "Loading catalogue…",
    "katalog.greska": "The catalogue can't be loaded right now.",
    "katalog.greska_uputa": "Try refreshing the page or write to us at",
    "katalog.ukloni_filtar": "remove filter",
    "katalog.filtri": "Filters",
    "katalog.aktivnih": "active:",

    "galerija.video": "{naziv} — video",
    "galerija.prikaz": "View {i} of {n}",
    "galerija.sve": "All",
    "galerija.svi_projekti": "All projects",
    "galerija.fotografija": { one: "photo", other: "photos" },
    "galerija.projekt": { one: "project", other: "projects" },
    "galerija.prazno": "No photos yet.",
    "galerija.greska": "The gallery can't be loaded right now.",
    "galerija.otvori": "Open photo: {opis}",
    "galerija.prethodna": "Previous photo",
    "galerija.sljedeca": "Next photo",
    "galerija.zatvori": "Close",
    "galerija.brojac": "{i} / {n}",

    "usluga.industrijske": "Industrial electrical installations",
    "usluga.zavrsni": "Finishing works",
    "usluga.kucne": "Residential electrical installations",
    "usluga.loxone": "Loxone smart home",

    "proizvod.prethodni": "Previous products",
    "proizvod.sljedeci": "Next products",

    "kosarica.naslov": "Cart",
    "kosarica.zatvori": "Close cart",
    "kosarica.prazna": "Your cart is empty.",
    "kosarica.prazna_uputa": "Add items from the Loxone catalogue or tool rental, then request a quote.",
    "kosarica.loxone_katalog": "Loxone catalogue",
    "kosarica.najam_alata": "Tool rental",
    "kosarica.ukloni": "Remove {naziv}",
    "kosarica.manje": "Decrease",
    "kosarica.vise": "Increase",
    "kosarica.razdoblje": "Period",
    "kosarica.sukob": "The tool is booked for the selected period.",
    "kosarica.sukobi": "The selected period is booked for {n}.",

    "najam.slobodno_danas": "Available today",
    "najam.slobodno_od": "Available from {datum}",
    "najam.vec_rezervirano": "Already booked:",

    "kalendar.prethodni": "Previous month",
    "kalendar.sljedeci": "Next month",
    "kalendar.zatvori": "Close calendar",
    "kalendar.odaberite_pocetak": "Choose the pick-up day.",
    "kalendar.odaberite_kraj": "Choose the return day.",
    "kalendar.ucitavanje": "Loading availability…",
    "kalendar.preuzimanje": "Pick-up",
    "kalendar.povrat": "Return",
    "kalendar.zauzeto": "booked",
    "kalendar.legenda_zauzeto": "Booked",
    "kalendar.ponisti": "Clear",
    "kalendar.potvrdi": "Apply",
    "kosarica.odaberite_datume": "Choose dates",
    "kosarica.ukupno": "Total",
    "kosarica.proizvodi": "Products",
    "kosarica.proizvodi_natpis": "Loxone · price per unit",
    "kosarica.najam_natpis": "price per day",
    "kosarica.ograda": "Estimate based on the price list. We send the final quote by email.",
    "kosarica.nedostaju_datumi": "Rental dates are missing for {n}.",
    "kosarica.zatrazite_ponudu": "Request a quote",
    "kosarica.isprazni": "Empty the cart",

    "izbornik.otvori": "Open menu",
    "izbornik.zatvori": "Close menu",

    "tema.na_svijetlu": "Switch to light theme",
    "tema.na_tamnu": "Switch to dark theme",

    "obrazac.spremno": "Ready to send",
    "obrazac.obavezno": "This field is required.",
    "obrazac.email": "Please check the email address.",
    "obrazac.poruka": "Briefly describe the job or your enquiry.",
    "obrazac.provjerite": "Please check the highlighted fields.",
    "obrazac.salje": "Sending…",
    "obrazac.poslano": "Your enquiry has been sent.",
    "obrazac.poslano_najam":
      "We are holding the dates for the tools in your cart for 48 hours. We will send the confirmation or our reply by email.",
    "obrazac.greska": "Your enquiry was not sent. Please try again or write to us at {email}.",
    "obrazac.zauzeto": "Already booked for the selected dates: {popis}. Change the dates in your cart and send again.",
    "obrazac.nedostupno": "No longer available: {popis}. Remove it from your cart and send again.",
    "obrazac.nedostaju_datumi": "Rental dates are missing in your cart.",
    "obrazac.otvori_kosaricu": "Open cart",
    "obrazac.kosarica": "The enquiry includes {n} from your cart.",
  },
};
